nome = input('Qual e o seu nome? ')
dia = input('Qual o dia que voce nasceu? ')
mes = input('Qual o mes que voce nasceu? ')
ano = input('Qual o ano que voce nasceu? ')
print('Ola,', nome, '! ')
print('Sua data de nascimento e: ', dia, '/', mes, '/', ano, '!')
